In [40]:
import pandas as pd

In [41]:
ds = pd.read_csv("Placement.csv")

In [42]:
#ds.info()

In [43]:
from Univariate import Univariate
Qual,Quan = Univariate.QualQuan(ds)

In [44]:
'''
qual , quan = [] , []
# Regular Method
for items in ds.columns:
    if ds[items].dtype == 'O':
        qual.append(items)
    else:
        quan.append(items)
# Optimized method
for items in ds.columns :
    (qual if ds[items].dtype == 'O' else quan).append(items)
# Function creation

def QualQuan(dataset) :
    for items in ds.columns :
        (qual if ds[items].dtype == 'O' else quan).append(items)
    return qual, quan

qual,quan = QualQuan(ds)
'''

"\nqual , quan = [] , []\n# Regular Method\nfor items in ds.columns:\n    if ds[items].dtype == 'O':\n        qual.append(items)\n    else:\n        quan.append(items)\n# Optimized method\nfor items in ds.columns :\n    (qual if ds[items].dtype == 'O' else quan).append(items)\n# Function creation\n\ndef QualQuan(dataset) :\n    for items in ds.columns :\n        (qual if ds[items].dtype == 'O' else quan).append(items)\n    return qual, quan\n\nqual,quan = QualQuan(ds)\n"

In [45]:
Qual

['gender',
 'ssc_b',
 'hsc_b',
 'hsc_s',
 'degree_t',
 'workex',
 'specialisation',
 'status']

In [46]:
Quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

# Central Tendency

In [47]:
ds["ssc_p"].mean() # Average Value

np.float64(67.30339534883721)

In [48]:
ds["ssc_p"].median() # Center Value

np.float64(67.0)

In [49]:
ds["ssc_p"].mode() # Repeated value

0    62.0
Name: ssc_p, dtype: float64

In [50]:
ds["ssc_p"].mode() [0]# Repeated value

np.float64(62.0)

In [51]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode"],columns=Quan)

In [52]:
descriptive

       sl_no ssc_p hsc_p degree_p etest_p mba_p salary
Mean     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Median   NaN   NaN   NaN      NaN     NaN   NaN    NaN
Mode     NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [57]:
descriptive.loc["ssc_p","Mode"]=0

In [74]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode"],columns=Quan)
for columnName in Quan:
    descriptive.loc["Mean",columnName]=ds[columnName].mean()
    descriptive.loc["Median",columnName]=ds[columnName].median()
    descriptive.loc["Mode",columnName]=ds[columnName].mode()[0]

In [75]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0

# Average mark of ssc ,hsc , degree is between 66-67.5, mba is 62 but in entrence they have scored 72
# Outlier of close to 23k present in Mean Salary value, identified through median 
# Repeated value of SSC is 62 and similarly for other features. repeated Salary for this set of people is 3lk.